"""Base de intencoes do chatbot: frases de treino e respostas possiveis por intencao."""

INTENCOES: dict[str, tuple[list[str], list[str]]] = {
    "saudacao": (
        [
            "ola",
            "bom dia",
            "boa tarde",
            "boa noite",
            "oi tudo bem",
            "hey",
            "opa",
            "eae",
            "e ai tudo certo",
            "olaa",
            "saudacoes",
        ],
        ["Ola! Como posso ajudar?", "Oi! Em que posso ser util hoje?"],
    ),
    "consultar_saldo": (
        [
            "quero ver meu saldo",
            "qual meu saldo",
            "saldo da conta",
            "quanto tenho na conta",
            "meu saldo atual",
            "verificar saldo",
            "como esta meu saldo",
            "saldo disponivel",
            "quanto sobrou na minha conta",
            "extrato resumido",
        ],
        ["Seu saldo atual e R$ 1.234,56.", "Voce possui R$ 1.234,56 disponiveis."],
    ),
    "fazer_transferencia": (
        [
            "quero transferir dinheiro",
            "fazer um ted",
            "transferir para outra pessoa",
            "enviar pix",
            "transferencia bancaria",
            "mandar dinheiro para alguem",
            "quero fazer um pix",
            "passar dinheiro pra minha mae",
            "transferir cem reais",
            "pix para um contato salvo",
        ],
        [
            "Para transferir, informe o valor e a chave do destinatario.",
            "Ok! Qual o valor e a chave (CPF, celular ou e-mail) do recebedor?",
        ],
    ),
    "segunda_via_fatura": (
        [
            "segunda via do boleto",
            "quero a fatura de novo",
            "reemitir fatura",
            "nao recebi meu boleto",
            "copia da fatura",
            "preciso da segunda via",
            "boleto vencido como pago",
            "gerar novo boleto",
            "reenviar o boleto",
            "imprimir a fatura deste mes",
        ],
        [
            "Enviei a segunda via para seu e-mail cadastrado.",
            "Segunda via gerada! Confira seu e-mail.",
        ],
    ),
    "reclamacao": (
        [
            "estou insatisfeito",
            "o servico e pessimo",
            "vou cancelar por incompetencia",
            "isso e um absurdo",
            "quero registrar uma reclamacao",
            "voces me enganaram",
            "atendimento horrivel",
            "nao resolvem meu problema",
            "estou muito insatisfeita",
            "servico ruim demais",
        ],
        ["Sinto muito pelo ocorrido. Vou abrir um protocolo prioritario para voce."],
    ),
    "falar_com_humano": (
        [
            "quero falar com atendente",
            "me passa um humano",
            "atendente real por favor",
            "falar com pessoa",
            "nao quero mais robô",
            "chama um atendente",
            "operador humano",
            "quero atendimento humano",
            "quero um supervisor",
            "pessoa de verdade pra me atender",
        ],
        ["Certo, estou transferindo para um atendente humano. Aguarde um instante."],
    ),
    "horario_atendimento": (
        [
            "qual o horario de atendimento",
            "voces abrem que horas",
            "funcionam aos sabados",
            "horario de funcionamento",
            "quando o banco abre",
            "atendem no domingo",
            "ate que horas ficam abertos",
            "agenda de atendimento",
            "que horas voce fecha",
            "abrem no feriado",
        ],
        ["Atendemos de seg a sex, das 8h as 20h, e sabados das 9h as 13h."],
    ),
    "despedida": (
        [
            "tchau",
            "obrigado ate logo",
            "valeu",
            "ate mais",
            "foi isso obrigado",
            "adeus",
            "falou",
            "brigadão",
            "obrigado tchau",
            "ate logo obrigado",
        ],
        ["Por nada! Ate a proxima.", "Foi um prazer ajudar. Tchau!"],
    ),
}
